USE [master]
GO

/****** Object:  Database [SupersChoice]    Script Date: 12/2/2020 6:00:20 PM ******/
CREATE DATABASE [SupersChoice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SupersChoice', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SupersChoice.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SupersChoice_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SupersChoice_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SupersChoice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SupersChoice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SupersChoice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SupersChoice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SupersChoice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SupersChoice] SET ARITHABORT OFF 
GO

ALTER DATABASE [SupersChoice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SupersChoice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SupersChoice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SupersChoice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SupersChoice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SupersChoice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SupersChoice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SupersChoice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SupersChoice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SupersChoice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SupersChoice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SupersChoice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SupersChoice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SupersChoice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SupersChoice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SupersChoice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SupersChoice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SupersChoice] SET RECOVERY FULL 
GO

ALTER DATABASE [SupersChoice] SET  MULTI_USER 
GO

ALTER DATABASE [SupersChoice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SupersChoice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SupersChoice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SupersChoice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SupersChoice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SupersChoice] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SupersChoice] SET  READ_WRITE 
GO

